#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    armPotent,      sensorPotentiometer)
#pragma config(Sensor, in2,    lineRight,      sensorLineFollower)
#pragma config(Sensor, in3,    lineCenter,     sensorLineFollower)
#pragma config(Sensor, in4,    lineLeft,       sensorLineFollower)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  frontTouch,     sensorTouch)
#pragma config(Sensor, dgtl6,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, dgtl8,  bumpTouch,      sensorTouch)
#pragma config(Sensor, dgtl12, led,            sensorLEDtoVCC)
#pragma config(Sensor, I2C_1,  rightIME,       sensorNone)
#pragma config(Sensor, I2C_2,  leftIME,        sensorNone)
#pragma config(Sensor, I2C_3,  armIME,         sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, driveLeft, encoderPort, dgtl3)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, reversed, driveRight, encoderPort, dgtl1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//int variables. Declare before use!
int left = 36;
int right = 30;
int dist = 15;
int turn = 250;
int turnspeed = 50;
int varspeed = vexRT[Ch2];
int varturn = vexRT[Ch1];
int sl = 600;
int sr = 605;

//void functions. Declare before use!
void goLeft()
{
	resetSensor(leftEncoder);
	resetSensor(rightEncoder);
	setMotor(leftMotor, turnspeed);
	setMotor(rightMotor, -turnspeed);
	waitUntil(SensorValue[rightEncoder] >= turn && SensorValue[leftEncoder] <= -turn);
	stopMultipleMotors(leftMotor, rightMotor);
	wait(20, milliseconds);
}

void goRight()
{
	resetSensor(leftEncoder);
	resetSensor(rightEncoder);
	setMotor(leftMotor, -turnspeed);
	setMotor(rightMotor, turnspeed);
	waitUntil(SensorValue[rightEncoder] <= -turn && SensorValue[leftEncoder] >= turn);
	stopMultipleMotors(leftMotor, rightMotor);
	wait(20, milliseconds);
}

void goForward()
{
	setMotor(leftMotor, left);
	setMotor(rightMotor, right);
	waitUntil(SensorValue[sonarSensor] <= dist);
	stopMultipleMotors(leftMotor, rightMotor);
}

void swingLeft()
{
	resetSensor(leftEncoder);
	resetSensor(rightEncoder);
	setMotor(leftMotor, 0);
	setMotor(rightMotor, turnspeed);
	waitUntil(SensorValue[leftEncoder] >= sl);
	stopMultipleMotors(leftMotor, rightMotor);
	wait(20, milliseconds);
}

void swingRight()
{
	resetSensor(leftEncoder);
	resetSensor(rightEncoder);
	setMotor(leftMotor, turnspeed);
	setMotor(rightMotor, 0);
	waitUntil(SensorValue[rightEncoder] >= sr);
	stopMultipleMotors(leftMotor, rightMotor);
	wait(20, milliseconds);
}

void leftCTRL()
{
	setMultipleMotors(varspeed, leftMotor, rightMotor);
	wait(20, milliseconds);
}

void forwardCTRL()
{

}

task main()
{
	swingLeft();
	wait(1000, milliseconds);
	swingRight();
	wait (1000,milliseconds);
}
