#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    armPotent,      sensorPotentiometer)
#pragma config(Sensor, in2,    lineRight,      sensorLineFollower)
#pragma config(Sensor, in3,    lineCenter,     sensorLineFollower)
#pragma config(Sensor, in4,    lineLeft,       sensorLineFollower)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  frontTouch,     sensorTouch)
#pragma config(Sensor, dgtl6,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, dgtl12, led,            sensorLEDtoVCC)
#pragma config(Sensor, I2C_1,  rightIME,       sensorNone)
#pragma config(Sensor, I2C_2,  leftIME,        sensorNone)
#pragma config(Sensor, I2C_3,  armIME,         sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, driveLeft, encoderPort, dgtl3)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, reversed, driveRight, encoderPort, dgtl1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int left = 50;
int right = 50;
int leftC = 100;
int rightC = 100;
int avoid = 2000;
int armspeed = 50;

void armlift()
{
	setMotor(armMotor, armspeed);
	waitUntil(SensorValue[armPotent] <= 1250);
	stopMotor(armMotor);
}
void goforward()
{
	setMotor(leftMotor, left);
	setMotor(rightMotor, right);
	wait(10, milliseconds);
}

void correctionL()
{
	setMotor(leftMotor, -left);
	setMotor(rightMotor, rightC);
	wait(10, milliseconds);
}

void correctionR()
{
	setMotor(leftMotor, leftC);
	setMotor(rightMotor, -right);
	wait(10, milliseconds);
}
task main()
{
	repeat(forever)
	{
		armlift();
		goforward();
		if(SensorValue[lineLeft] >= avoid)
		{
			correctionR();
		}
		if(SensorValue[lineRight] >= avoid)
		{
			correctionL();
		}
	}
}
