#pragma config(I2C_U***sage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, in2,    centerLineFollower, sensorLineFollower)
#pragma config(Sensor, in3,    rightLineFollower, sensorLineFollower)
#pragma config(Sensor, in6,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  touchSensor,    sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, dgtl11, armEncoder,     sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  rightIME,       sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  leftIME,        sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  armIME,         sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, driveLeft, encoderPort, I2C_2)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, reversed, driveRight, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	waitUntil (vexRT[Btn7U] == 1);
	repeat (forever) {
		if (vexRT[Btn7D] == 1) {
			stopAllMotors();*
			waitUntil (vexRT[Btn7U] == 1);
			//* If 7D is pressed, it stops the robot until 7U is pressed *//
			//* again, in which the program will restart *//
			} else {
			//* Assuming everything works, this'll move the robot through *//
			//* the maze. *//
			forward(2900, milliseconds, 25);
			turnRight(1700, milliseconds, 31);
			forward(4275, milliseconds, 25);
			turnLeft(1500, milliseconds, 31);
			forward(2375, milliseconds, 25);
			turnLeft(1600, milliseconds, 31);
			forward(2000, milliseconds, 25);
			waitUntil(vexRT[Btn6U] == 1);
			//* Waits until someone presses 6U (Right top sholder button) *//
			//* which meand the program will start all over again. *//
		}
	}
}
