#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, in2,    centerLineFollower, sensorLineFollower)
#pragma config(Sensor, in3,    rightLineFollower, sensorLineFollower)
#pragma config(Sensor, in6,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  frontTouch,     sensorTouch)
#pragma config(Sensor, dgtl6,  bumpTouch,      sensorTouch)
#pragma config(Sensor, dgtl12, led,            sensorLEDtoVCC)
#pragma config(Sensor, I2C_1,  rightIME,       sensorNone)
#pragma config(Sensor, I2C_2,  leftIME,        sensorNone)
#pragma config(Sensor, I2C_3,  armIME,         sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, driveLeft, encoderPort, dgtl3)
#pragma config(Motor,  port6,           clawMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           armMotor,      tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_3)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, reversed, driveRight, encoderPort, dgtl1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int speed = 100;
	int clawspeed = 40;
	int armspeed = 100;
	repeat(forever)
	{
		if(vexRT[Btn7U] == 1)
		{
			setMultipleMotors(speed, rightMotor, leftMotor);
			waitUntil(vexRT[Btn7U] == 0);
			stopMultipleMotors(leftMotor, rightMotor);
		}
		if(vexRT[Btn7D] == 1)
		{
			setMultipleMotors(-speed, rightMotor, leftMotor);
			waitUntil(vexRT[Btn7D] == 0);
			stopMultipleMotors(leftMotor, rightMotor);
		}
		if(vexRT[Btn7L] == 1)
		{
			setMotor(leftMotor, speed);
			setMotor(rightMotor, -speed);
			waitUntil(vexRT[Btn7L] == 0);
			stopMultipleMotors(leftMotor, rightMotor);
		}
		if(vexRT[Btn7R] == 1)
		{
			setMotor(leftMotor, -speed);
			setMotor(rightMotor, speed);
			waitUntil(vexRT[Btn7R] == 0);
			stopMultipleMotors(leftMotor, rightMotor);
		}
		if(vexRT[Btn5U] == 1)
		{
			setMotor(clawMotor, clawspeed);
			waitUntil(vexRT[Btn5U] == 0);
			stopMotor(clawMotor);
		}
		if(vexRT[Btn5D] == 1)
		{
			setMotor(clawMotor, -clawspeed);
			waitUntil(vexRT[Btn5D] == 0);
			stopMotor(clawMotor);
		}
		if(vexRT[Btn6U] == 1)
		{
			setMotor(armMotor, armspeed);
			waitUntil(vexRT[Btn6U] == 0);
			stopMotor(armMotor);
		}
		if(vexRT[Btn6D] == 1)
		{
			setMotor(armMotor, -armspeed);
			waitUntil(vexRT[Btn6D] == 0);
			stopMotor(armMotor);
		}
	}
}
